services:
  postgres:
    image: postgres:17-alpine
    container_name: sass_starter_core_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ca3c3458c150656a38701bf606b9a212
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: