services:
  postgres:
    image: postgres:17-alpine
    container_name: sass_starter_core_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 42b92a2b3d68bcf3ae6ce1f40303c123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: